services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION}
    container_name: zilla
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
      - 7151:7151
      - 7183:7183
      - 7190:7190
    environment:
      ROUTE_GUIDE_SERVER_HOST: route-guide-server
      ROUTE_GUIDE_SERVER_PORT: 50051
      KAFKA_BOOTSTRAP_SERVERS: "pkc-p11xm.us-east-1.aws.confluent.cloud:9092"
      KAFKA_USERNAME: "JSS7COGL3ZC4Z5HE"
      KAFKA_PASSWORD: "H/TiBxBMbBsg2TK1uhhZTbKvoljKU1pRAFDkTZV2Hb1Fcc38rXCsDAQk/JH4H3J2"
    volumes:
      - ../../zilla.yaml:/etc/zilla/zilla.yaml
      - ./proto/:/etc/zilla/proto/
    command: start -v -e -Pzilla.engine.worker.capacity=512

  mqtt-simulator:
    image: ghcr.io/vordimous/mqtt-simulator:zilla-quickstart
    container_name: mqtt-simulator
    restart: unless-stopped
    volumes:
      - ./sim_settings.json:/usr/src/app/config/settings.json

  route-guide-server:
    image: ghcr.io/aklivity/extras-route-guide-server:sha-e49c994
    container_name: route-guide-server
    restart: unless-stopped
    ports:
      - 50051:50051

networks:
  default:
    driver: bridge
